{"uuid": "935e4743-d674-409b-a0fc-dfe13da7119b", "children": ["34762486-878f-4880-93b9-f64313271784"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\n", "trace": "  File \"c:\\users\\arumugam\\pycharmprojects\\ecommerce_demo\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\arumugam\\pycharmprojects\\ecommerce_demo\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\arumugam\\pycharmprojects\\ecommerce_demo\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Arumugam\\PycharmProjects\\ECommerce_Demo\\testCases\\conftest.py\", line 19, in setup\n    web_driver = webdriver.Firefox()\n  File \"c:\\users\\arumugam\\pycharmprojects\\ecommerce_demo\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 164, in __init__\n    self.service.start()\n  File \"c:\\users\\arumugam\\pycharmprojects\\ecommerce_demo\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1635728281458, "stop": 1635728281739}], "start": 1635728281458, "stop": 1635728282286}